name: bet_sim
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - backcall=0.2.0
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=2.1.0
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.12.2
  - jedi=0.19.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - libcxx=14.0.6
  - libffi=3.4.4
  - libsodium=1.0.18
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.3.2
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.8.19
  - python_abi=3.8
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=63.4.1
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
  - pip:
      - confseq==0.0.6
      - contourpy==1.1.1
      - cycler==0.12.1
      - dill==0.3.8
      - exceptiongroup==1.2.2
      - fonttools==4.53.1
      - importlib-resources==6.4.5
      - iniconfig==2.0.0
      - kiwisolver==1.4.7
      - matplotlib==3.7.5
      - multiprocess==0.70.16
      - numpy==1.24.4
      - pandas==2.0.3
      - pillow==10.4.0
      - pluggy==1.5.0
      - pybind11==2.13.6
      - pyparsing==3.1.4
      - pytest==8.3.3
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - qmcpy==1.6.2
      - qmctoolscl==1.1.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - tomli==2.0.1
      - tzdata==2024.1
prefix: /opt/miniconda3/envs/bet_sim
